# Dependabot will run on day 7 of each month at 01:52 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "52 1 7 * *"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "52 1 7 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/src-rx"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "52 1 7 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
